#ifndef VEINHELPERS_GLOBAL_H
#define VEINHELPERS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VEINHELPERS_LIBRARY)
#  define VEINHELPERSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VEINHELPERSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VEINHELPERS_GLOBAL_H
